<script lang="ts">
	import { writable } from 'svelte/store';
	import * as fal from '@fal-ai/serverless-client';

	fal.config({
		// NOTE: client-side credentials are not recommended for production use
		// credentials: ''
		proxyUrl: '/api/fal/proxy'
	});

	type Image = {
		url: string;
		file_name: string;
		file_size: number;
	};

	type Result = {
		images: Image[];
	};

	const DEFAULT_PROMPT =
		'a city landscape of a cyberpunk metropolis, raining, purple, pink and teal neon lights, highly detailed, uhd';

	// Page state
	const prompt = writable<string>(DEFAULT_PROMPT);
	const loading = writable<boolean>(false);
	const error = writable<Error | null>(null);
	const generatedImage = writable<Result | null>(null);
	const logs = writable<string[]>([]);
	const elapsedTime = writable<number>(0);

	function reset() {
		loading.set(false);
		error.set(null);
		generatedImage.set(null);
		logs.set([]);
		elapsedTime.set(0);
	}

	// Function to generate image
	async function generateImage() {
		const start = Date.now();
		reset();
		loading.set(true);

		try {
			const result: Result = await fal.subscribe('fal-ai/lora', {
				input: {
					prompt: $prompt,
					model_name: 'stabilityai/stable-diffusion-xl-base-1.0',
					image_size: 'square_hd'
				},
				pollInterval: 3000,
				logs: true,
				onQueueUpdate(update) {
					elapsedTime.set(Date.now() - start);
					if (update.status === 'IN_PROGRESS' || update.status === 'COMPLETED') {
						logs.set((update.logs || []).map((log) => log.message));
					}
				}
			});
			generatedImage.set(result);
		} catch (e: any) {
			error.set(e);
		} finally {
			loading.set(false);
		}
	}
</script>

<main class="container mx-auto py-8 space-y-4">
	<div class="space-y-4">
		<input
			class="w-full text-lg p-2 rounded dark:text-white/80 bg-black/10 dark:bg-white/5 border border-black/20 dark:border-white/10"
			placeholder="Enter a prompt"
			bind:value={$prompt}
			on:input={(e) => ($prompt = e?.currentTarget?.value ?? '')}
		/>
		<button
			class="bg-indigo-600 hover:bg-indigo-700 text-white font-bold text-lg py-3 px-6 mx-auto rounded focus:outline-none focus:shadow-outline"
			on:click={generateImage}>Generate</button
		>
	</div>
	{#if $loading && !$generatedImage}
		<p class="dark:text-white/80">Loading...</p>
	{/if}
	{#if $error}
		<div class="text-red-600">Error: {$error.message}</div>
	{/if}
	{#if $generatedImage}
		<img src={$generatedImage.images[0].url} alt="generated by fal.ai" />
	{/if}
</main>

<style>
	/* Your CSS here */
</style>
